categories:
  videoShariff:
    label: 'video-shariff'

settings:
  videoShariff.defaultThumbnail:
      type: string
      label: 'Default thumbnail when no video specific thumbnail can be fetched'
      default: 'EXT:video_shariff/Resources/Public/Images/DefaultThumbnail.png'
